require("basic-lua-extensions")
require("functions")
--require("config")

require("items")
require("entities")
require("technology")

require("prototypes.item-groups")
require("prototypes.fast-long-inserter")
require("prototypes.recycler")
require("prototypes.electric-recycler")
require("prototypes.dirt-marker")
require("prototypes.harder-iron-processing")
require("prototypes.crusher")
require("prototypes.pulverizer")