require("basic-lua-extensions")
require("functions")
--require("config")

require("prototypes.item-groups")
require("prototypes.fast-long-inserter")
require("prototypes.recycler")
require("prototypes.electric-recycler")
require("prototypes.harder-iron-processing")
require("prototypes.harder-copper-processing")