require("basic-lua-extensions")
require("functions")
--require("config")

require("prototypes.fast-long-inserter")
require("prototypes.recycler")
require("prototypes.electric-recycler")
require("prototypes.harder-iron-processing")
require("prototypes.harder-copper-processing")
require("prototypes.engines-and-robots")
require("prototypes.easier-but-more-trains")